name: ml_toolkit
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/ic_launcher_background.webp"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.webp"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    favicon_path: "assets/icon/favicon.ico"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/screenshots/
    - assets/docs/
    - assets/icon/
    - assets/app.json
    - assets/config.json
